packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
